name: Deploy Workflow
on:
  push:
    branches:
      - main
      - dev
      - test
jobs:
  test:
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
    runs-on: ubuntu-latest
    environment: Personal-Blog-Environment
    env:
      FLASK_KEY: ${{ secrets.FLASK_KEY }}
      DB_URI: postgresql+psycopg2://test:test@localhost:5432/test_db
    steps:
      - name: Get Code
        uses: actions/checkout@v6
      - name: Create virtual environment
        run: | 
          python3 -m venv .venv
          source .venv/bin/activate
      - name: Install depencencies
        run: |
          pip install -r requirements.txt
      - name: Wait for Postgres
        run: |
          until pg_isready -h localhost -p 5432 -U test; do
            echo "Waiting for Postgres..."
            sleep 1
          done
      - name: Run the app
        run: |
          nohup python3 main.py & sleep 5
      - name: Perform health check (the app is up and running; the process did not crash)
        run: |
          curl -f http://127.0.0.1:5000/health
      - name: Readiness check
        run: |
          curl -f http://127.0.0.1:5000/ready