name: Deploy Workflow
on:
  push:
    branches:
      - main
      - dev
      - test
  pull_request:
    branches:
      - main
      - dev
      - test
jobs:
  test:
    runs-on: ubuntu-latest
    environment: Personal-Blog-Environment
    env:
      FLASK_KEY: ${{ secrets.FLASK_KEY }}
    steps:
      - name: Get Code
        uses: actions/checkout@v6
      - name: Create virtual environment
        run: | 
          python3 -m venv .venv
          source .venv/bin/activate
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with pylint
        run: |
          pylint project/**/*.py --disable=R0903
      - name: Lint with flake8
        run: |
          flake8 project/
      - name: Run tests with pytest
        run: |
          pytest -v tests/unit/
          pytest -v tests/functional
      - name: Run the app and perform health check
        run: |
          nohup python3 -m project.main & sleep 5
          curl -f http://127.0.0.1:5000/
          
